### ISSUE TITLE
Update base image (conda 4.5.11 and R)

### ISSUE THREAD

**Issue by aurelien-naldi** [colomoto/colomoto-docker-base#4]
For the next version, I propose to:
* update miniconda to 4.5.11
* Include seaborn (an extra layer on top of matplotlib)
* Include R to pave the way for Boolnet and CellNopt

I can apply the first two changes quickly but I'm not sure about R yet.
Is there some other pending change to include in the next base image?

**Comment by pauleve** [comment]
For R, we should do it in a separate branch for now (`R` for instance) - hub.docker will create automatically a tag 'R' for it, so we can use it to test colomoto-docker images (in a `next-R` branch of it).

As for miniconda 4.5.11, it ships python 3.7 but it seems we have some dependencies which force a downgrade to 3.6 (at least clingo). So I'll suggest to keep the current version as is, and just include seaborn (and upgrade pydot, issue #3 ) the time everything works with python 3.7.

**Comment by pauleve** [comment]
I've included seaborn and upgraded miniconda to 4.5.11 in the master branch and made a tag `v1.3`.
For the conda upgrade, actually the downgrade to python 3.6 is done already in the base image, so it should be harmless..
although the image is 90MB bigger (I'm not sure if this is solely due to seaborn) ; I'll try to investigate why..

As for R, I created a `R` branch with `r` and `rpy` packages ; it is 160MB bigger than `v1.2` and 70MB bigger than `v1.3`.
In colomoto/colomoto-docker there is now a `next-R` branch in which you can try integrating BoolNet and CellNopt.

https://hub.docker.com/r/colomoto/colomoto-docker-base/tags/

**Comment by pauleve** [comment]
So the 90MB difference seems due to seaborn (and probably pulled dependencies) ; but I agree it is a standard library worth to include in the base image, so be it.
